/*
Base de datos Sustantivos.pl
Desarrolado por: Olman rodríguez, Joan Ugalde y Andres Rayo
Tarea 2
Descripción: Base de datos donde se encuentran todos los
sustantivo(plurales, singulares, femeninos y masculinos)
Instituto
Tecnológico de Costa Rica
Lenguajes, Compiladores e
Interpretes
*/
sustantivo(singular, masculino, ["adorno"], ["ornament"]).
sustantivo(singular, masculino, ["amanecer"], ["dawn"]).
sustantivo(singular, masculino, ["amor"], ["love"]).
sustantivo(singular, masculino, ["apunte"], ["note"]).
sustantivo(singular, masculino, ["aarbol"], ["tree"]).
sustantivo(singular, masculino, ["automoovil"], ["car"]).
sustantivo(singular, masculino, ["boliigrafo"], ["pen"]).
sustantivo(singular, masculino, ["cafee"], ["coffee"]).
sustantivo(singular, masculino, ["calor"], ["heat"]).
sustantivo(singular, masculino, ["camaleoon"], ["chameleon"]).
sustantivo(singular, masculino, ["camino"], ["way"]).
sustantivo(singular, masculino, ["carpincho"], ["capybara"]).
sustantivo(singular, masculino, ["carruaje"], ["carriage"]).
sustantivo(singular, masculino, ["celular"], ["cell phone"]).
sustantivo(singular, masculino, ["color"], ["color"]).
sustantivo(singular, masculino, ["coro"], ["chorus"]).
sustantivo(singular, masculino, ["corredor"], ["corridor"]).
sustantivo(singular, masculino, ["cuaderno"], ["notebook"]).
sustantivo(singular, masculino, ["dolor"], ["pain"]).
sustantivo(singular, masculino, ["domingo"], ["sunday"]).
sustantivo(singular, masculino, ["hormiguero"], ["anthill"]).
sustantivo(singular, masculino, ["leoon"], ["lion"]).
sustantivo(singular, masculino, ["libro"], ["book"]).
sustantivo(singular, masculino, ["mate"], ["mate"]).
sustantivo(singular, masculino, ["mieercoles"], ["wednesday"]).
sustantivo(singular, masculino, ["monitor"], ["monitor"]).
sustantivo(singular, masculino, ["norte"], ["north"]).
sustantivo(singular, masculino, ["oreegano"], ["oregano"]).
sustantivo(singular, masculino, ["pan"], ["bread"]).
sustantivo(singular, masculino, ["pannuelo"], ["handkerchief"]).
sustantivo(singular, masculino, ["parto"], ["childbirth"]).
sustantivo(singular, masculino, ["perejil"], ["parsley"]).
sustantivo(singular, masculino, ["pincel"], ["brush"]).
sustantivo(singular, masculino, ["pollo"], ["chicken"]).
sustantivo(singular, masculino, ["roedor"], ["rodent"]).
sustantivo(singular, masculino, ["sendero"], ["trail"]).
sustantivo(singular, masculino, ["sol"], ["sun"]).
sustantivo(singular, masculino, ["sosteen"], ["bra"]).
sustantivo(singular, masculino, ["sur"], ["south"]).
sustantivo(singular, masculino, ["sistema"], ["system"]).
sustantivo(singular, masculino, ["taladro"], ["drill"]).
sustantivo(singular, masculino, ["tee"], ["tea"]).
sustantivo(singular, masculino, ["teclado"], ["keyboard"]).
sustantivo(singular, masculino, ["zorro"], ["fox"]).
sustantivo(singular, masculino, ["universo"], ["universe"]).
/*
%femenino
sustantivo(singular, femenino, ["accioon"], ["action"]).
sustantivo(singular, femenino, ["actriz"], ["actress"]).
sustantivo(singular, femenino, ["barbarie"], ["barbarism"]).
sustantivo(singular, femenino, ["cancioon"], ["song"]).
sustantivo(singular, femenino, ["carpa"], ["carp"]).
sustantivo(singular, femenino, ["cocina"], ["kitchen"]).
sustantivo(singular, femenino, ["costumbre"], ["custom"]).
sustantivo(singular, femenino, ["crisis"], ["crisis"]).
sustantivo(singular, femenino, ["edad"], ["age"]).
sustantivo(singular, femenino, ["esfinge"], ["sphinx"]).
sustantivo(singular, femenino, ["eternidad"], ["eternity"]).
sustantivo(singular, femenino, ["fiesta"], ["party"]).
sustantivo(singular, femenino, ["hiena"], ["hyena"]).
sustantivo(singular, femenino, ["hija"], ["daughter"]).
sustantivo(singular, femenino, ["leona"], ["lioness"]).
sustantivo(singular, femenino, ["liebre"], ["hare"]).
sustantivo(singular, femenino, ["luna"], ["moon"]).
sustantivo(singular, femenino, ["mansioon"], ["mansion"]).
sustantivo(singular, femenino, ["medalla"], ["medal"]).
sustantivo(singular, femenino, ["mesa"], ["table"]).
sustantivo(singular, femenino, ["metamorfosis"], ["metamorphosis"]).
sustantivo(singular, femenino, ["muchedumbre"], ["crowd"]).
sustantivo(singular, femenino, ["nariz"], ["nose"]).
sustantivo(singular, femenino, ["nuera"], ["daughter in law"]).
sustantivo(singular, femenino, ["nutria"], ["otter"]).
sustantivo(singular, femenino, ["paraalisis"], ["paralysis"]).
sustantivo(singular, femenino, ["pasioon"], ["passion"]).
sustantivo(singular, femenino, ["perdiz"], ["partridge"]).
sustantivo(singular, femenino, ["pieza"], ["piece"]).
sustantivo(singular, femenino, ["pintura"], ["painting"]).
sustantivo(singular, femenino, ["pinna"], ["pineapple"]).
sustantivo(singular, femenino, ["planta"], ["plant"]).
sustantivo(singular, femenino, ["prima"], ["cousin"]).
sustantivo(singular, femenino, ["princesa"], ["princess"]).
sustantivo(singular, femenino, ["programacioon"], ["programming"]).
sustantivo(singular, femenino, ["raiiz"], ["root"]).
sustantivo(singular, femenino, ["reina"], ["queen"]).
sustantivo(singular, femenino, ["serie"], ["serie"]).
sustantivo(singular, femenino, ["sintaxis"], ["syntax"]).
sustantivo(singular, femenino, ["suegra"], ["mother in law"]).
sustantivo(singular, femenino, ["superficie"], ["surface"]).
sustantivo(singular, femenino, ["tabla"], ["board"]).
sustantivo(singular, femenino, ["tarjeta"], ["card"]).
sustantivo(singular, femenino, ["taza"], ["cup"]).
sustantivo(singular, femenino, ["televisioon"], ["television"]).
sustantivo(singular, femenino, ["universidad"], ["university"]).
sustantivo(singular, femenino, ["vaca"], ["cow"]).
sustantivo(singular, femenino, ["voz"], ["voice"]).
sustantivo(singular, femenino, ["yegua"], ["mare"]).

%masculino plural
sustantivo(plural, masculino, ["abuelos"], ["grandparents"]).
sustantivo(plural, masculino, ["acroobatas"], ["acrobats"]).
sustantivo(plural, masculino, ["alfileres"], ["pins"]).
sustantivo(plural, masculino, ["algodones"], ["cottons"]).
sustantivo(plural, masculino, ["almuerzos"], ["lunches"]).
sustantivo(plural, masculino, ["alumnos"], ["students"]).
sustantivo(plural, masculino, ["amigos"], ["friends"]).
sustantivo(plural, masculino, ["amores"], ["loves"]).
sustantivo(plural, masculino, ["anillos"], ["rings"]).
sustantivo(plural, masculino, ["annos"], ["years"]).
sustantivo(plural, masculino, ["asientos"], ["seats"]).
sustantivo(plural, masculino, ["aatomos"], ["atoms"]).
sustantivo(plural, masculino, ["autos"], ["cars"]).
sustantivo(plural, masculino, ["aviones"], ["airplanes"]).
sustantivo(plural, masculino, ["bannos"], ["bathrooms"]).
sustantivo(plural, masculino, ["barcos"], ["ships"]).
sustantivo(plural, masculino, ["barriletes"], ["kites"]).
sustantivo(plural, masculino, ["bebees"], ["babies"]).
sustantivo(plural, masculino, ["bombones"], ["chocolates"]).
sustantivo(plural, masculino, ["botones"], ["buttons"]).
sustantivo(plural, masculino, ["brillos"], ["glitters"]).
sustantivo(plural, masculino, ["caballos"], ["horses"]).
sustantivo(plural, masculino, ["cables"], ["cables"]).
sustantivo(plural, masculino, ["calcetines"], ["socks"]).
sustantivo(plural, masculino, ["caminos"], ["ways"]).
sustantivo(plural, masculino, ["campos"], ["fields"]).
sustantivo(plural, masculino, ["caramelos"], ["candies"]).
sustantivo(plural, masculino, ["cartones"], ["cartons"]).
sustantivo(plural, masculino, ["cepillos"], ["brushes"]).
sustantivo(plural, masculino, ["cerdos"], ["pigs"]).
sustantivo(plural, masculino, ["cimientos"], ["foundations"]).
sustantivo(plural, masculino, ["cinturones"], ["belts"]).
sustantivo(plural, masculino, ["ciirculos"], ["circles"]).
sustantivo(plural, masculino, ["claveles"], ["carnations"]).
sustantivo(plural, masculino, ["cocodrilos"], ["crocodiles"]).
sustantivo(plural, masculino, ["colegios"], ["schools"]).
sustantivo(plural, masculino, ["colores"], ["colors"]).
sustantivo(plural, masculino, ["conceptos"], ["concepts"]).
sustantivo(plural, masculino, ["condimentos"], ["condiments"]).
sustantivo(plural, masculino, ["consejos"], ["advices"]).
sustantivo(plural, masculino, ["corazones"], ["hearts"]).
sustantivo(plural, masculino, ["cuadernos"], ["notebooks"]).
sustantivo(plural, masculino, ["cuchillos"], ["knives"]).
sustantivo(plural, masculino, ["cuerpos"], ["bodies"]).
sustantivo(plural, masculino, ["dannos"], ["damages"]).
sustantivo(plural, masculino, ["dedos"], ["fingers"]).
sustantivo(plural, masculino, ["depeesitos"], ["deposits"]).
sustantivo(plural, masculino, ["diias"], ["days"]).
sustantivo(plural, masculino, ["diamantes"], ["diamonds"]).
sustantivo(plural, masculino, ["diccionarios"], ["dictionaries"]).
sustantivo(plural, masculino, ["dioses"], ["gods"]).
sustantivo(plural, masculino, ["doctores"], ["doctors"]).
sustantivo(plural, masculino, ["doolares"], ["dollars"]).
sustantivo(plural, masculino, ["dolores"], ["pains"]).
sustantivo(plural, masculino, ["edificios"], ["buildings"]).
sustantivo(plural, masculino, ["ejemplos"], ["examples"]).
sustantivo(plural, masculino, ["equipos"], ["teams"]).
sustantivo(plural, masculino, ["esos"], ["those"]).
sustantivo(plural, masculino, ["estudiantes"], ["students"]).
sustantivo(plural, masculino, ["exaamenes"], ["exams"]).
sustantivo(plural, masculino, ["futuros"], ["futures"]).
sustantivo(plural, masculino, ["gatos"], ["cats"]).
sustantivo(plural, masculino, ["geeneros"], ["genders"]).
sustantivo(plural, masculino, ["gobiernos"], ["governments"]).
sustantivo(plural, masculino, ["grupos"], ["groups"]).
sustantivo(plural, masculino, ["hermanos"], ["brothers"]).
sustantivo(plural, masculino, ["heeroes"], ["heroes"]).
sustantivo(plural, masculino, ["hijos"], ["children"]).
sustantivo(plural, masculino, ["hogares"], ["households"]).
sustantivo(plural, masculino, ["hombres"], ["men"]).
sustantivo(plural, masculino, ["huecos"], ["holes"]).
sustantivo(plural, masculino, ["invitados"], ["guests"]).
sustantivo(plural, masculino, ["jabones"], ["soaps"]).
sustantivo(plural, masculino, ["jardines"], ["gardens"]).
sustantivo(plural, masculino, ["juegos"], ["games"]).
sustantivo(plural, masculino, ["juguetes"], ["toys"]).
sustantivo(plural, masculino, ["lados"], ["sides"]).
sustantivo(plural, masculino, ["lagos"], ["lakes"]).
sustantivo(plural, masculino, ["laapices"], ["pencils"]).
sustantivo(plural, masculino, ["lenguajes"], ["languages"]).
sustantivo(plural, masculino, ["libros"], ["books"]).
sustantivo(plural, masculino, ["logros"], ["achievements"]).
sustantivo(plural, masculino, ["manantiales"], ["springs"]).
sustantivo(plural, masculino, ["mares"], ["seas"]).
sustantivo(plural, masculino, ["meses"], ["months"]).
sustantivo(plural, masculino, ["minutos"], ["minutes"]).
sustantivo(plural, masculino, ["muebles"], ["furniture"]).
sustantivo(plural, masculino, ["negocios"], ["business"]).
sustantivo(plural, masculino, ["ninnos"], ["children"]).
sustantivo(plural, masculino, ["niveles"], ["levels"]).
sustantivo(plural, masculino, ["nuumeros"], ["numbers"]).
sustantivo(plural, masculino, ["objetivos"], ["objectives"]).
sustantivo(plural, masculino, ["objetos"], ["objects"]).
sustantivo(plural, masculino, ["ojos"], ["eyes"]).
sustantivo(plural, masculino, ["padres"], ["parents"]).
sustantivo(plural, masculino, ["paiises"], ["countries"]).
sustantivo(plural, masculino, ["pajaros"], ["birds"]).
sustantivo(plural, masculino, ["papeles"], ["papers"]).
sustantivo(plural, masculino, ["parques"], ["parks"]).
sustantivo(plural, masculino, ["perioodicos"], ["newspapers"]).
sustantivo(plural, masculino, ["presidentes"], ["presidents"]).
sustantivo(plural, masculino, ["problemas"], ["problems"]).
sustantivo(plural, masculino, ["productos"], ["products"]).
sustantivo(plural, masculino, ["profesores"], ["teachers"]).
sustantivo(plural, masculino, ["pueblos"], ["villages"]).
sustantivo(plural, masculino, ["regalos"], ["gifts"]).
sustantivo(plural, masculino, ["riios"], ["rivers"]).
sustantivo(plural, masculino, ["emparedados"], ["sandwiches"]).
sustantivo(plural, masculino, ["segundos"], ["seconds"]).
sustantivo(plural, masculino, ["siglos"], ["ages"]).
sustantivo(plural, masculino, ["sistemas"], ["systems"]).
sustantivo(plural, masculino, ["soles"], ["suns"]).
sustantivo(plural, masculino, ["sonidos"], ["sounds"]).
sustantivo(plural, masculino, ["suelos"], ["soils"]).
sustantivo(plural, masculino, ["techos"], ["roofs"]).
sustantivo(plural, masculino, ["teleefonos"], ["telephones"]).
sustantivo(plural, masculino, ["televisores"], ["tvs"]).
sustantivo(plural, masculino, ["tomates"], ["tomatoes"]).
sustantivo(plural, masculino, ["tenedores"], ["forks"]).
sustantivo(plural, masculino, ["terremotos"], ["earthquakes"]).
sustantivo(plural, masculino, ["terrenos"], ["lands"]).
sustantivo(plural, masculino, ["trabajos"], ["works"]).
sustantivo(plural, masculino, ["tratamientos"], ["treatments"]).
sustantivo(plural, masculino, ["trucos"], ["tricks"]).
sustantivo(plural, masculino, ["vasos"], ["cups"]).
sustantivo(plural, masculino, ["vecinos"], ["neighbors"]).
sustantivo(plural, masculino, ["vestidos"], ["dresses"]).
sustantivo(plural, masculino, ["vinos"], ["wines"]).
sustantivo(plural, masculino, ["visitantes"], ["visitors"]).
sustantivo(plural, masculino, ["zapatos"], ["shoes"]).

%femenino plural
sustantivo(plural, femenino, ["actitudes"], ["actitudes"]).
sustantivo(plural, femenino, ["alfombras"], ["carpets"]).
sustantivo(plural, femenino, ["ausencias"], ["absences"]).
sustantivo(plural, femenino, ["bibliotecas"], ["libraries"]).
sustantivo(plural, femenino, ["bicicletas"], ["bicycles"]).
sustantivo(plural, femenino, ["bolas"], ["balls"]).
sustantivo(plural, femenino, ["bufandas"], ["scarfs"]).
sustantivo(plural, femenino, ["caiidas"], ["falls"]).
sustantivo(plural, femenino, ["cajas"], ["boxes"]).
sustantivo(plural, femenino, ["calculadoras"], ["calculators"]).
sustantivo(plural, femenino, ["calles"], ["streets"]).
sustantivo(plural, femenino, ["camas"], ["beds"]).
sustantivo(plural, femenino, ["caamaras"], ["cameras"]).
sustantivo(plural, femenino, ["camisas"], ["shirts"]).
sustantivo(plural, femenino, ["capas"], ["layers"]).
sustantivo(plural, femenino, ["caarceles"], ["prisions"]).
sustantivo(plural, femenino, ["carpetas"], ["folders"]).
sustantivo(plural, femenino, ["carreras"], ["races"]).
sustantivo(plural, femenino, ["cartas"], ["letters"]).
sustantivo(plural, femenino, ["casas"], ["houses"]).
sustantivo(plural, femenino, ["cebras"], ["zebras"]).
sustantivo(plural, femenino, ["cenas"], ["dinners"]).
sustantivo(plural, femenino, ["cervezas"], ["beers"]).
sustantivo(plural, femenino, ["ciudades"], ["cities"]).
sustantivo(plural, femenino, ["cocinas"], ["kitchens"]).
sustantivo(plural, femenino, ["comidas"], ["meals"]).
sustantivo(plural, femenino, ["competencias"], ["skills"]).
sustantivo(plural, femenino, ["computadoras"], ["computers"]).
sustantivo(plural, femenino, ["conversaciones"], ["conversations"]).
sustantivo(plural, femenino, ["corbatas"], ["ties"]).
sustantivo(plural, femenino, ["cosas"], ["things"]).
sustantivo(plural, femenino, ["cucharas"], ["spoons"]).
sustantivo(plural, femenino, ["decoraciones"], ["decorations"]).
sustantivo(plural, femenino, ["direcciones"], ["directions"]).
sustantivo(plural, femenino, ["distancias"], ["distances"]).
sustantivo(plural, femenino, ["emergencias"], ["emergencies"]).
sustantivo(plural, femenino, ["energiias"], ["energies"]).
sustantivo(plural, femenino, ["esas"], ["those"]).
sustantivo(plural, femenino, ["escuelas"], ["schools"]).
sustantivo(plural, femenino, ["esculturas"], ["sculptures"]).
sustantivo(plural, femenino, ["esferas"], ["spheres"]).
sustantivo(plural, femenino, ["esquinas"], ["corners"]).
sustantivo(plural, femenino, ["estrellas"], ["stars"]).
sustantivo(plural, femenino, ["evidencias"], ["evidence"]).
sustantivo(plural, femenino, ["flores"], ["flowers"]).
sustantivo(plural, femenino, ["fiestas"], ["parties"]).
sustantivo(plural, femenino, ["faldas"], ["skirts"]).
sustantivo(plural, femenino, ["galletas"], ["coockies"]).
sustantivo(plural, femenino, ["guerras"], ["wars"]).
sustantivo(plural, femenino, ["guitarras"], ["guitars"]).
sustantivo(plural, femenino, ["habitaciones"], ["rooms"]).
sustantivo(plural, femenino, ["hermanas"], ["sisters"]).
sustantivo(plural, femenino, ["hierbas"], ["herbs"]).
sustantivo(plural, femenino, ["hijas"], ["daughters"]).
sustantivo(plural, femenino, ["hojas"], ["leaves"]).
sustantivo(plural, femenino, ["horas"], ["hours"]).
sustantivo(plural, femenino, ["ideas"], ["ideas"]).
sustantivo(plural, femenino, ["iglesias"], ["churches"]).
sustantivo(plural, femenino, ["industrias"], ["industries"]).
sustantivo(plural, femenino, ["informaciones"], ["informations"]).
sustantivo(plural, femenino, ["injusticias"], ["injustices"]).
sustantivo(plural, femenino, ["islas"], ["islands"]).
sustantivo(plural, femenino, ["laamparas"], ["lamps"]).
sustantivo(plural, femenino, ["lesiones"], ["lesions"]).
sustantivo(plural, femenino, ["letras"], ["letters"]).
sustantivo(plural, femenino, ["leyes"], ["laws"]).
sustantivo(plural, femenino, ["llaves"], ["keys"]).
sustantivo(plural, femenino, ["lunas"], ["moons"]).
sustantivo(plural, femenino, ["luces"], ["lights"]).
sustantivo(plural, femenino, ["maletas"], ["suitcases"]).
sustantivo(plural, femenino, ["manos"], ["hands"]).
sustantivo(plural, femenino, ["mantas"], ["blankets"]).
sustantivo(plural, femenino, ["manzanas"], ["apples"]).
sustantivo(plural, femenino, ["mascotas"], ["pets"]).
sustantivo(plural, femenino, ["mentiras"], ["lies"]).
sustantivo(plural, femenino, ["mujeres"], ["women"]).
sustantivo(plural, femenino, ["ninnas"], ["girls"]).
sustantivo(plural, femenino, ["notas"], ["notes"]).
sustantivo(plural, femenino, ["nubes"], ["clouds"]).
sustantivo(plural, femenino, ["oficinas"], ["offices"]).
sustantivo(plural, femenino, ["ollas"], ["pots"]).
sustantivo(plural, femenino, ["orejas"], ["ears"]).
sustantivo(plural, femenino, ["orquestas"], ["orchestras"]).
sustantivo(plural, femenino, ["paaginas"], ["pages"]).
sustantivo(plural, femenino, ["palabras"], ["words"]).
sustantivo(plural, femenino, ["pantallas"], ["screens"]).
sustantivo(plural, femenino, ["paredes"], ["walls"]).
sustantivo(plural, femenino, ["pastillas"], ["pills"]).
sustantivo(plural, femenino, ["peliiculas"], ["movies"]).
sustantivo(plural, femenino, ["pelotas"], ["balls"]).
sustantivo(plural, femenino, ["personas"], ["people"]).
sustantivo(plural, femenino, ["pinturas"], ["paintings"]).
sustantivo(plural, femenino, ["preguntas"], ["questions"]).
sustantivo(plural, femenino, ["propiedades"], ["properties"]).
sustantivo(plural, femenino, ["pruebas"], ["tests"]).
sustantivo(plural, femenino, ["puertas"], ["doors"]).
sustantivo(plural, femenino, ["reglas"], ["rules"]).
sustantivo(plural, femenino, ["respuestas"], ["answers"]).
sustantivo(plural, femenino, ["reuniones"], ["meetings"]).
sustantivo(plural, femenino, ["rocas"], ["rocks"]).
sustantivo(plural, femenino, ["serpientes"], ["snakes"]).
sustantivo(plural, femenino, ["sillas"], ["chairs"]).
sustantivo(plural, femenino, ["sustancias"], ["substances"]).
sustantivo(plural, femenino, ["tazas"], ["cups"]).
sustantivo(plural, femenino, ["tejas"], ["tiles"]).
sustantivo(plural, femenino, ["temporadas"], ["seasons"]).
sustantivo(plural, femenino, ["tiendas"], ["stores"]).
sustantivo(plural, femenino, ["tierras"], ["lands"]).
sustantivo(plural, femenino, ["urgencias"], ["emergencies"]).
sustantivo(plural, femenino, ["vacas"], ["cows"]).
sustantivo(plural, femenino, ["vacantes"], ["vacancies"]).
sustantivo(plural, femenino, ["ventanas"], ["windows"]).
sustantivo(plural, femenino, ["vidas"], ["lifes"]).
sustantivo(plural, femenino, ["zanahorias"], ["carrots"]).
*/
