sustantivo(singular, masculino, "adorno", "ornament").
sustantivo(singular, masculino, "amanecer", "dawn").
sustantivo(singular, masculino, "amor", "love").
sustantivo(singular, masculino, "apunte", "note").
sustantivo(singular, masculino, "árbol", "tree").
sustantivo(singular, masculino, "automóvil", "car").
sustantivo(singular, masculino, "bolígrafo", "pen").
sustantivo(singular, masculino, "café", "coffee").
sustantivo(singular, masculino, "calor", "heat").
sustantivo(singular, masculino, "camaleón", "chameleon").
sustantivo(singular, masculino, "camino", "way").
sustantivo(singular, masculino, "carpincho", "capybara").
sustantivo(singular, masculino, "carruaje", "carriage").
sustantivo(singular, masculino, "celular", "cell phone").
sustantivo(singular, masculino, "color", "color").
sustantivo(singular, masculino, "coro", "chorus").
sustantivo(singular, masculino, "corredor", "corridor").
sustantivo(singular, masculino, "cuaderno", "notebook").
sustantivo(singular, masculino, "dolor", "pain").
sustantivo(singular, masculino, "domingo", "sunday").
sustantivo(singular, masculino, "hormiguero", "anthill").
sustantivo(singular, masculino, "león", "lion").
sustantivo(singular, masculino, "libro", "book").
sustantivo(singular, masculino, "mate", "mate").
sustantivo(singular, masculino, "miércoles", "wednesday").
sustantivo(singular, masculino, "monitor", "monitor").
sustantivo(singular, masculino, "norte", "north").
sustantivo(singular, masculino, "orégano", "oregano").
sustantivo(singular, masculino, "pan", "bread").
sustantivo(singular, masculino, "pañuelo", "handkerchief").
sustantivo(singular, masculino, "parto", "childbirth").
sustantivo(singular, masculino, "perejil", "parsley").
sustantivo(singular, masculino, "pincel", "brush").
sustantivo(singular, masculino, "pollo", "chicken").
sustantivo(singular, masculino, "roedor", "rodent").
sustantivo(singular, masculino, "sendero", "trail").
sustantivo(singular, masculino, "sol", "sun").
sustantivo(singular, masculino, "sostén", "bra").
sustantivo(singular, masculino, "sur", "south").
sustantivo(singular, masculino, "taladro", "drill").
sustantivo(singular, masculino, "té", "tea").
sustantivo(singular, masculino, "teclado", "keyboard").
sustantivo(singular, masculino, "zorro", "fox").

%femenino
sustantivo(singular, femenino, "acción", "action").
sustantivo(singular, femenino, "actriz", "actress").
sustantivo(singular, femenino, "barbarie", "barbarism").
sustantivo(singular, femenino, "canción", "song").
sustantivo(singular, femenino, "carpa", "carp").
sustantivo(singular, femenino, "cocina", "kitchen").
sustantivo(singular, femenino, "costumbre", "custom").
sustantivo(singular, femenino, "crisis", "crisis").
sustantivo(singular, femenino, "edad", "age").
sustantivo(singular, femenino, "esfinge", "sphinx").
sustantivo(singular, femenino, "eternidad", "eternity").
sustantivo(singular, femenino, "fiesta", "party").
sustantivo(singular, femenino, "hiena", "hyena").
sustantivo(singular, femenino, "hija", "daughter").
sustantivo(singular, femenino, "leona", "lioness").
sustantivo(singular, femenino, "liebre", "hare").
sustantivo(singular, femenino, "luna", "moon").
sustantivo(singular, femenino, "mansión", "mansion").
sustantivo(singular, femenino, "medalla", "medal").
sustantivo(singular, femenino, "mesa", "table").
sustantivo(singular, femenino, "metamorfosis", "metamorphosis").
sustantivo(singular, femenino, "muchedumbre", "crowd").
sustantivo(singular, femenino, "nariz", "nose").
sustantivo(singular, femenino, "nuera", "daughter in law").
sustantivo(singular, femenino, "nutria", "otter").
sustantivo(singular, femenino, "parálisis", "paralysis").
sustantivo(singular, femenino, "pasión", "passion").
sustantivo(singular, femenino, "perdiz", "partridge").
sustantivo(singular, femenino, "pieza", "piece").
sustantivo(singular, femenino, "pintura", "painting").
sustantivo(singular, femenino, "piña", "pineapple").
sustantivo(singular, femenino, "planta", "plant").
sustantivo(singular, femenino, "prima", "cousin").
sustantivo(singular, femenino, "princesa", "princess").
sustantivo(singular, femenino, "raíz", "root").
sustantivo(singular, femenino, "reina", "queen").
sustantivo(singular, femenino, "serie", "serie").
sustantivo(singular, femenino, "sintaxis", "syntax").
sustantivo(singular, femenino, "suegra", "mother in law").
sustantivo(singular, femenino, "superficie", "surface").
sustantivo(singular, femenino, "tabla", "board").
sustantivo(singular, femenino, "tarjeta", "card").
sustantivo(singular, femenino, "taza", "cup").
sustantivo(singular, femenino, "televisión", "television").
sustantivo(singular, femenino, "universidad", "university").
sustantivo(singular, femenino, "vaca", "cow").
sustantivo(singular, femenino, "voz", "voice").
sustantivo(singular, femenino, "yegua", "mare").

%masculino plural

